config/routes.rb
Rails.application.routes.draw do

  #configure devise 
  devise_scope :user do
   post '/' => "users/sessions#login"
   get '/' => "users/sessions#login"
   post "/login" => "users/sessions#create"
   get "/login" => "users/sessions#create"
   post '/register' => 'users/registrations#create'
   get '/register' => 'users/registrations#create'

   # Overwrite existing device login form
   get '/users/sign_up' => 'users/sessions#register'
   get '/users/sign_in' => 'users/sessions#login'
   
   delete '/sign_out' => 'users/sessions#destroy'            
 end

 devise_for :users, controllers: { sessions: 'users/sessions' }
 root 'users/sessions#login'

 # Navigation links
 post '/tutorials' => "users/search#home"
 get '/tutorials' => "users/search#home"

 post '/search' => "users/search#home"
 get '/search' => "users/search#home"

 post '/test_page' => "users/test#home"
 get '/test_page' => "users/test#home"

 # Articles 
 post '/articles/article1' => "articles/articles#article1"
 get '/articles/article1' => "articles/articles#article1"

 post '/articles/article2' => "articles/articles#article2"
 get '/articles/article2' => "articles/articles#article2"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
      added_attrs = [:email, :password, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs      
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
   end
end

app/controllers/articles/articles_controller.rb
class Articles::ArticlesController < ApplicationController   

   def article1
      render template: "articles/article1"
   end

   def article2
      render template: "articles/article2"
   end


end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new    
    super    
  end

  # POST /resource
  def create    
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to search_path        
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to root_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # overwrite Devise redirect
  def destroy
   signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
   set_flash_message! :notice, :signed_out if signed_out
   redirect_to root_url   
 end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController   
   before_action :authenticate_user!

   def home
      # @developer_key = ENV['GOOGLE_PICKER_DEVELOPER_KEY']
      # @client_id = ENV['GOOGLE_PICKER_CLIENT_ID']
      # @app_id = ENV['APPLICAITON_ID']
      render template: "users/search"      
   end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]  
  before_action :require_no_authentication, only: :cancel
  
  # overwrite default Devise routing
  def login    
    render template: "sessions/login"
  end

  def register    
    render template: "sessions/login"
  end
  # GET /resource/sign_in
  def new        
    super    
  end

  # POST /resource/sign_in
  # overwrite Devise redirect paths
  def create    
    auth_options = { :recall => 'users/sessions#login', :scope => :user }
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil      
    else
      redirect_to search_path
    end    
  end

  # DELETE /resource/sign_out
  def destroy
    super
    # signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    # set_flash_message! :notice, :signed_out if signed_out
    # redirect_to root_url   
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/test_controller.rb
class Users::TestController < ApplicationController
   # THIS IS A SESSION RESTRICTED AREA 
   before_action :authenticate_user!

   def home
      render template: "users/test_page"
      
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/article1.html.erb
<div class="container article-container">
   <div class=" col-9">
      <div class="row">
         <h1>How to design beautiful responsive emails</h1>      
         
         <div class="row">
            <div class="col-8">
               <p>MJML is a framework for developing responsive email templates which are render correctly across a wide range of email providers, web browsers and operating systems. It is even compatible with Outlook!
               </p>


               <p>MJML can either be used locally via “Node Package Manager” or in a provided online text editor with a life visual preview.
               </p>

               <p><a href="https://mjml.io/try-it-live">Live editor</a>. And this is its <a href="https://mjml.io/documentation/">Documentation</a>.</p>
            </div>
            <div class="col-4">
               <img src="https://i1.wp.com/rubyauthority.com/wp-content/uploads/2019/01/email.png?zoom=1.5&resize=208%2C208" class="img-rounded img-fluid" alt="email">
            </div>
         </div>
         <p>Walkthrough Example:</p>

         <p>MJML utilizes a grid system. < mj-section> enables us to put content into a row whereas < mj-column> enables us to display content next to each other in columns within a particular row. Width of the columns is shared evenly by default i.e. with 2 columns next to each other, each will occupy 50% of the space. The width of a row is 600px by default.</p>

         <p> To insert custom HTML elements we would use the MJML tag < mj-text>. Within this tag we can specify our own HTML elements. Let’s look at an example. Say we want to display an image of a product with a URL, product description and product price all next to each other. Our code could look something like this. 
         </p>
         
         <img src="https://i0.wp.com/rubyauthority.com/wp-content/uploads/2019/01/img1.png" class="img-rounded img-fluid mb-2" alt="code screenshot">

         <p>First we create a row by using < mj-section> tag. Within this tag we then create 3 columns using < mj-column>. As our description of a product is much longer than the price of a product we decide to allocate more space to this column specifying attribute width < mj-column width=”250”> Notice that we don’t add units (e.g. pixels) and that the total width of all columns adds up to 600 (as we have mentioned previously the width of a row is 600px). For other MJML attributes please refer to the documentation. Those shown in this example should be largely self-explanatory. To create URL links and to embed these into a picture we need to use classic HTML. This we can do by nesting our HTML code in the < mj-text> tag.
         </p>

         <img src="https://i0.wp.com/rubyauthority.com/wp-content/uploads/2019/01/img2.png?fit=666%2C191" class="img-rounded img-fluid mb-2" alt="code screenshot">

         <p>Notice, that we were able to use a very straight forward syntax while MJML ensures that the HTML code will display correctly on various browsers and email clients. Typically we would need to write a complicated structure with several nested HTML tables to ensure a correct display particularly in Outlook.            
         </p>

         <p>In the example above we have contained some CSS styling directly to our HTML using attribute “Style”. We can also write our CSS code in the “head section” as follows:           
         </p>

         <img src="https://i1.wp.com/rubyauthority.com/wp-content/uploads/2019/01/img3.png" class="img-rounded img-fluid mb-2" alt="code screenshot">         

         <p>Note that the CSS will apply only to HTML elements and will have no impact on the MJML tags. To style MJML tags we need to use the supported attributes. As can be seen from the examples, we can directly embed Jinja into the code. However Jinja used outside of the MJML elements (e.g. cycles) will be discarded.            
         </p>



      </div>
   </div>

app/views/articles/article2.html.erb
<div class="container article-container">
   <div class=" col-9">
      <div class="row">
         <h1>Setting up Sublime Text</h1>
         
         <div class="row">
            <div class="col-8">
               <p>Spending a little bit of time setting up your working environment will save you a lot of time during your work. It will also help you to do your work well as with the right set up it will be easy to discover mistakes in your code such as missing closing tags. And finally setting up Sublime is very easy and you will surely love the results.
               </p>
            </div>
            <div class="col-4">
               <img src="https://i1.wp.com/rubyauthority.com/wp-content/uploads/2018/07/Sublime-logo.png?zoom=1.5&resize=208%2C208" width="150px" class="img-rounded img-fluid" alt="Sublime Text Icon">
            </div>
         </div>
         <h2>Installing package manager</h2>
         <p>There are two parts to setting up Sublime Text. The largest part of it will be done through third party packages. To be able to access them we first need to install the Sublime Package manager. Simply copy the provided code from the <a href="https://packagecontrol.io/installation">official page</a> and paste it into your console in Sublime Text.</p>
         
         <img src="https://i1.wp.com/rubyauthority.com/wp-content/uploads/2018/07/Sublime-show-console.png?fit=749%2C632" class="img-rounded img-fluid mb-2" alt="Sublime screenshot">
         <p>This will install the required files (don’t worry, they don’t take up much space). Now you are ready to install any packages you like. Let’s look at some of the most useful ones.
         </p>
         <h2>Installing packages</h2>
         <p>To install a package simply press “ctrl + shift + p”, then type in “install package”, press “enter” and you will be prompted to type in a name of the desired package.
         </p>
         <img src="https://i0.wp.com/rubyauthority.com/wp-content/uploads/2018/07/install-package.png?fit=1024%2C443" class="img-rounded img-fluid mb-2" alt="Sublime screenshot">
         <h2>Reindent on save</h2>
         <p>Try typing in <a href="https://packagecontrol.io/packages/Reindent%20on%20save"> reindent on save </a>. This is the name of one the best packages. You simply install it and forget about it. Every time you save your file, the package will automatically reindent your files. I can’t imagine working without it as it saves you a lot of time on formatting and makes it much easier for you to navigate through your code and identify any mistakes. The package works great with HTML, CSS and JavaScript. In my experience it does a poorer job with Ruby.
         </p>
         <h2>CSS3</h2>
         <p>This is a package which helps you to complete your CSS code as you type in. It also highlights your CSS code based on “best practices” and makes your code more readable.
         </p>

         <h2>All Autocomplete</h2>
         <p><a href="https://www.sublimetext.com/docs/3/auto_complete.html">All Autocomplete</a> helps you to complete code as you type it. It is particularly useful for writing HTML as it helps you to close your tags. As with all these packages it has much more to offer but it does require a little bit of researching and experimentation. To disable filling suggested on pressing enter.</p>
         <h2>Java Script Completions</h2>
         <p>To help you complete your Java Script code as you are typing it use the <a href="https://packagecontrol.io/packages/JavaScript%20Completions">Java Script Completions</a> package. Similarly <strong>Ruby Completions</strong> and <strong>Rails Completions</strong> do the job for Ruby on Rails code!</p>
         <h2>Bracket Highlighter</h2>
         <p>This is a package particularly useful when typing Ruby code. It not only show you the other of a two brackets but also helps you to match the beginning and an end of loops, if statements, classes and the like.</p>

         <h2>Styling Sublime Text</h2>
         <p>There are also several packages which enable you to style your Sublime Text itself. You can change for example the background color, size of your currently open tabs, width of indentation, width of spacing etc. While the bellow suggested packages will help you to do some of these things, they will require you to go into the “JSON user-settings” of your Sublime Text editor. Here you can specifically configure the behavior of these packages (as well as those packages previously mentioned) and you can also change some of the default settings of your Sublime Text editor.</p>
         <p>This is a great <a href="https://www.youtube.com/watch?v=oHmPrjSzmwU">video tutorial</a> which will walk you through the necessary steps. Enjoy!</p>
         <h2>Material Theme</h2>

         <p>This <a href="https://packagecontrol.io/packages/Theme%20-%20Dark%20Material">package</a> enables you to style the look of your text editor. You can use it to set up your text editor the way you like it. Stronger contrasts between colors may be pleasant and make it easier to navigate your way around. Many people prefer light background but I find dark background less tiring for eyes.</p>
         <h2>SideBarEnhancements</h2>
         <p>This package adds additional functionality to your side bar. You can now easily create new files, move and rename your existing files and much more. Give it a try yourself.</p>
         <h2>Tips</h2>
         <ul>
            <li>To run your Java Script code in a console press “ctrl + b”. While debugging with Google Chrome Development Tools is great, sometimes seeing your JS only in Sublime Text is more convenient. To close the console again, simply press “Escape”.
            </li>
         </ul>
         <img src="https://i0.wp.com/rubyauthority.com/wp-content/uploads/2018/07/JSConsole-output.png?resize=897%2C745" class="img-rounded img-fluid mb-2" alt="Sublime screenshot">
         <ul>
            <li>To navigate between different tabs press “ctrl + tab”. Unlike web browser, Sublime doesn’t go over your tabs from left to right but rather in order depending on your usage of them. Very clever.
            </li>
            <li>
               “ctrl + alt + arrow up/down” enables you to type on several lines at the same time. Particularly useful when systematically changing classes of multiple elements underneath each other.
            </li>
         </ul>

         <img src="https://i2.wp.com/rubyauthority.com/wp-content/uploads/2018/07/multiline-change.png?resize=1024%2C335" class="img-rounded img-fluid mb-2" alt="Sublime screenshot">

         <h2>Summary</h2>
         <p>These were just some of the packages I find the most useful and particularly easy to use. I don’t know all the great packages out there and I have intentionally skipped some of the most popular ones (as their use may not be intuitive for beginner programmers). Play around with them and find out which of them work well for you. When you are not satisfied with the way your Sublime Text editor works, you can always uninstall any package by launching the package manager with “ctrl + shift + p” and typing “uninstall package” (then “enter” followed by the name of the package you wish to uninstall). Similarly, you can also access the list of all your installed packages. What are your favorite Sublime packages?</p>
      </div>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digital World</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <!-- <li class="nav-item">
            <%= link_to "Banner Builder", "/", method: :post, class: "nav-link"%>
          </li> -->
          <% end %>
          <li class="nav-item">
            <%= link_to "Store", "/", method: :post, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Articles", "/test_page", method: :get, class: "nav-link"%>
          </li>
          
          <li class="nav-item">
            <%= link_to "Free Resources", "/", method: :post, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Portfolio", "/portfolio", method: :post, class: "nav-link"%>
          </li>
          <% if user_signed_in? %>
          <!-- <li class="nav-item">
            <%= link_to "Sign Out", "/sign_out", method: :delete, class: "nav-link"%>
          </li>       -->
          <% end %>
        </ul>
      </div>
    </nav>    
    <div class="jumbotron jumbotron-fluid">
      <div class="container-fluid">
        <h1>Digital World</h1>
        <p>Complete Toolkit for the 21st century Entrepreneur</p>
        <div class="container">
          <%= form_tag("/email_submit", method: "post") do %>
          
          <div class="row col-sm-12 col-md-6 offset-1 offset-md-3 offset-lg-3">
            <%= text_field_tag("email", value = nil, options = {class: "form-control email-subscription-input col-10 col-sm-6 col-md-8 col-lg-7", placeholder: "email@address.com"}) %>
            <%= submit_tag("Sign Up", class: "btn btn-success col-10 col-sm-3 offset-sm-1 col-md-3 submit-button") %>
          </div>
          
          <%= label_tag(:subscription, "Sign Up for weekly newsletter", class: "text-center mt-3") %>
          
          <% end %>
        </div>
      </div>
    </div>

    <%= yield %>
    
  </body>
  </html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/search.html.erb
<!-- 
<div class="col-sm-12 offset-5">
  <button class="btn btn-success" id="gdrive-button">Open Google Drive</button>
</div>

<script type="text/javascript" src="https://apis.google.com/js/api.js"></script>
<script type="text/javascript">

  document.getElementById("gdrive-button").addEventListener("click", function(event){
    event.preventDefault();    
    loadPicker();
  });
  
    // The Browser API key obtained from the Google API Console.
    // Replace with your own Browser API key, or your own key.    
    var developerKey = '<%= @developer_key %>';

    // The Client ID obtained from the Google API Console. Replace with your own Client ID.
    var clientId = '<%= @client_id %>';

    // Replace with your own project number from console.developers.google.com.
    // See "Project number" under "IAM & Admin" > "Settings"
    var appId = '<%= @app_id %>';

    // Scope to use to access user's Drive items.
    var scope = ['https://www.googleapis.com/auth/drive'];    
    var pickerApiLoaded = false;
    var oauthToken;

    // Use the Google API Loader script to load the google.picker script.
    function loadPicker() {      
      gapi.load('auth', {'callback': onAuthApiLoad});
      gapi.load('picker', {'callback': onPickerApiLoad});
    }

    function onAuthApiLoad() {
      window.gapi.auth.authorize(
      {
        'client_id': clientId,
        'scope': scope,
        'immediate': false
      },
      handleAuthResult);
    }

    function onPickerApiLoad() {
      pickerApiLoaded = true;
      createPicker();
    }

    function handleAuthResult(authResult) {
      if (authResult && !authResult.error) {
        oauthToken = authResult.access_token;
        createPicker();
      }
    }

    // Create and render a Picker object for searching images.
    function createPicker() {
      if (pickerApiLoaded && oauthToken) {
        //View all the documents of a Specific folder of Google drive        
        var downloadView = new google.picker.DocsView().setParent('1fJhppKeZkC_U6iLGmQn1FBAQOUxYiEn2');
        var uploadView = new google.picker.DocsUploadView().setParent('1fJhppKeZkC_U6iLGmQn1FBAQOUxYiEn2') 
        downloadView.setMimeTypes("text/plain");             
        uploadView.setMimeTypes("text/plain");             
        var picker = new google.picker.PickerBuilder()
        // .setStarred(true);
        // .setLabel("Starred");
        // .enableFeature(google.picker.Feature.NAV_HIDDEN)
        // .enableFeature(google.picker.Feature.MULTISELECT_ENABLED)
        .setAppId(appId)
        .setOAuthToken(oauthToken)
        .addView(downloadView)     
        .addView(uploadView)                
        // .addView(new google.picker.DocsUploadView())
        .setDeveloperKey(developerKey)
        .setCallback(pickerCallback)
        .build();
        picker.setVisible(true);
      }
    }        

    // Callback function
    function pickerCallback(data) {
      var html = [];
      var url;
      var action = data[google.picker.Response.ACTION];
      if (action == google.picker.Action.PICKED) {
        var documents = data[google.picker.Response.DOCUMENTS];
        for (var i = 0 ; i < documents.length ; i++) {
          // THERE WILL BE A PROBLEM WITH MULTIPLE SELECTED FILES
          url = documents[i][google.picker.Document.URL];
          html.push([           
            documents[i][google.picker.Document.URL]
            ].join("\t"));    
        }
      } else if (action == google.picker.Action.CANCEL) {
        html.push("No file selected");
      }      
      // Prevent empty callback
      if(url){
        openURLInNewTab(url);  
      }      
    }

    function showMessage(message){      
      document.getElementById("result").innerHTML = message;
    }
    function openURLInNewTab(url){
      window.open(url, '_blank').focus();      
    }

  </script>

  <div id="result"></div>  
  < !-- <script type="text/javascript" src="https://apis.google.com/js/api.js?onload=loadPicker"></script> -->